version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: psal_psql_14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker:/var/lib/postgresql/data
    ports:
      - "6432:5432"
