# Generated by Django 4.1.4 on 2023-04-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_init_university_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="title",
            field=models.CharField(
                help_text="Название статуса университета", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="domain",
            field=models.CharField(
                help_text="Основной домен (сайт) университета",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="geo_point",
            field=models.CharField(
                help_text="Геоточка нахождения университета", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="universitystatus",
            name="university",
            field=models.ForeignKey(
                help_text="Ссылка на университет",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="university.university",
            ),
        ),
    ]
