# Generated by Django 4.1.4 on 2023-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_forgotten_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="inn",
            field=models.CharField(
                blank=True, help_text="ИНН", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="ogrn",
            field=models.CharField(
                blank=True, help_text="ОРГН", max_length=13, null=True
            ),
        ),
    ]
