# Generated by Django 4.1.4 on 2023-03-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_init_geo_tables"),
        ("university", "0001_init_university_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(help_text="Дата курса обмена валюты")),
                (
                    "title",
                    models.CharField(help_text="Название валюты", max_length=255),
                ),
                (
                    "nominal",
                    models.IntegerField(help_text="Номинал (сколько в рублях)"),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="Курс обмена (сколько можно получить в валюте за номинал)"
                    ),
                ),
                (
                    "char_code",
                    models.CharField(
                        help_text="Текстовый код из 3-х символов", max_length=3
                    ),
                ),
                ("num_code", models.IntegerField(help_text="Номерной код валюты")),
                (
                    "currency_id",
                    models.CharField(
                        help_text="ID валюты (указано в атрибуте тега валюты в XML)",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "hh_currency_exchange_rate",
            },
        ),
        migrations.CreateModel(
            name="HHUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hh_employer_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID организации как работодателя",
                        null=True,
                    ),
                ),
                (
                    "hh_university_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID организации как университета",
                        null=True,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        help_text="Ссылка на университет",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="university.university",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "HH universities",
                "db_table": "hh_hh_university",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("hh_id", models.IntegerField(help_text="ID вакансии в HH")),
                (
                    "hh_created_at",
                    models.DateTimeField(help_text="Дата и время публикации вакансии"),
                ),
                (
                    "hh_initial_created_at",
                    models.DateTimeField(help_text="Дата и время создания вакансии"),
                ),
                (
                    "title",
                    models.CharField(help_text="Наименование вакансии", max_length=255),
                ),
                ("description", models.TextField(help_text="Описание вакансии")),
                (
                    "salary_from",
                    models.FloatField(
                        blank=True, help_text="Заработная плата «от»", null=True
                    ),
                ),
                (
                    "salary_to",
                    models.FloatField(
                        blank=True, help_text="Заработная плата «до»", null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        blank=True,
                        help_text="3-х символьный код валюты (принудительно приводится к RUR)",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "salary_gross",
                    models.BooleanField(
                        blank=True,
                        help_text="Признак того что оклад указан до вычета налогов",
                        null=True,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        help_text="Требуемый опыт работы (без нормализации)",
                        max_length=25,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="График работы (без нормализации)", max_length=25
                    ),
                ),
                (
                    "employment",
                    models.CharField(
                        help_text="Тип занятости (без нормализации)", max_length=25
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Ссылка на страницу вакансии на HH", max_length=255
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(help_text="Баккет в S3", max_length=255),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="Ссылка на JSON вакансии полученный от HH",
                        max_length=255,
                    ),
                ),
                (
                    "federal_region",
                    models.ForeignKey(
                        help_text="Ссылка на регион",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geo.federalregion",
                    ),
                ),
                (
                    "hh_university",
                    models.ForeignKey(
                        help_text="Ссылка на HH университет",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hh.hhuniversity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancies",
                "db_table": "hh_vacancy",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Название ключевого навыка", max_length=255
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="Ссылка на вакансию",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hh.vacancy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfessionalRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hh_professional_role_dict_id",
                    models.IntegerField(
                        help_text="Ссылка на справочник профессиональных ролей в HH"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название ключевого навыка", max_length=255
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="Ссылка на вакансию",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hh.vacancy",
                    ),
                ),
            ],
            options={
                "db_table": "hh_professional_role",
            },
        ),
    ]
