# Generated by Django 4.1.4 on 2023-04-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_forgotten_migrations"),
        ("hh", "0001_init_hh_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hhuniversity",
            name="university",
            field=models.ForeignKey(
                help_text="Ссылка на университет",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hh",
                to="university.university",
            ),
        ),
        migrations.AlterField(
            model_name="professionalrole",
            name="vacancy",
            field=models.ForeignKey(
                help_text="Ссылка на вакансию",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professional_role",
                to="hh.vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="vacancy",
            field=models.ForeignKey(
                help_text="Ссылка на вакансию",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skill",
                to="hh.vacancy",
            ),
        ),
    ]
