# Generated by Django 4.2.3 on 2024-01-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_init_geo_tables"),
        ("hh", "0002_forgotten_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="federal_region",
            field=models.ForeignKey(
                blank=True,
                help_text="Ссылка на регион РФ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.federalregion",
            ),
        ),
    ]
