# Generated by Django 4.1.4 on 2023-02-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Название города", max_length=255),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="FederalRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Название региона", max_length=255),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("republic", "Республика"),
                            ("edge", "Край"),
                            ("area", "Область"),
                            ("city", "Город федерального значения"),
                            ("region", "Регион"),
                            ("okrug", "Автономный округ"),
                        ],
                        help_text="Тип региона",
                        max_length=27,
                    ),
                ),
                ("square", models.FloatField(help_text="Площадь региона")),
                ("okato", models.IntegerField(help_text="ОКАТО")),
                (
                    "capital",
                    models.ForeignKey(
                        help_text="Столица региона",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geo.city",
                    ),
                ),
            ],
            options={
                "db_table": "geo_federal_region",
            },
        ),
        migrations.CreateModel(
            name="FederalDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Название федерального округа", max_length=255
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        help_text="Краткое название федерального округа", max_length=255
                    ),
                ),
                ("square", models.FloatField(help_text="Площадь федерального округа")),
                (
                    "capital",
                    models.ForeignKey(
                        help_text="Столица федерального округа",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geo.city",
                    ),
                ),
            ],
            options={
                "db_table": "geo_federal_district",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="federal_district",
            field=models.ForeignKey(
                help_text="Федеральный округ",
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.federaldistrict",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="federal_region",
            field=models.ForeignKey(
                help_text="Регион",
                on_delete=django.db.models.deletion.PROTECT,
                to="geo.federalregion",
            ),
        ),
    ]
