# Generated by Django 4.1.4 on 2023-05-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("university", "0002_forgotten_migrations"),
        ("dict", "0001_add_oecd_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(help_text="Название типа актива", max_length=255),
                ),
                (
                    "title_short",
                    models.CharField(
                        help_text="Краткое название типа актива", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "rosrid_active_type",
            },
        ),
        migrations.CreateModel(
            name="RosridUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rosrid_id",
                    models.CharField(
                        help_text="ID организации в ЕГИСУ НИОКТР",
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        help_text="Ссылка на университет",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rosrid",
                        to="university.university",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "RosRID universities",
                "db_table": "rosrid_rosrid_university",
            },
        ),
        migrations.CreateModel(
            name="Active",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_id",
                    models.CharField(
                        help_text="Уникальный ID актива внутри ЕГИСУ НИОКТР",
                        max_length=25,
                    ),
                ),
                ("date", models.DateField(help_text="Дата из ЕГИСУ НИОКТР")),
                (
                    "title",
                    models.CharField(help_text="Название актива", max_length=2048),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Ссылка на актив в ЕГИСУ НИОКТР", max_length=255
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(help_text="Баккет в S3", max_length=255),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="Ссылка на JSON содержащий подробные данные актива",
                        max_length=255,
                    ),
                ),
                (
                    "oecd",
                    models.ManyToManyField(help_text="Связи с OECD", to="dict.oecd"),
                ),
                (
                    "rosrid_university",
                    models.ForeignKey(
                        help_text="Ссылка на университет в ЕГИСУ НИОКТР",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rosrid.rosriduniversity",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Ссылка на тип актива",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rosrid.activetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
