# Generated by Django 4.1.4 on 2023-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_news_feed_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsfeed",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
